### ISSUE TITLE
SIHUMI example error with colonocyte

### ISSUE THREAD

**Issue by thh32** [maringos/VirtualColon#1]
Hey,

When running the example code I get the error:

```
Error in colonocyte[[which(names(colonocyte) == simulation_sequence$Sample[j])]] : 
  attempt to select less than one element in get1index
```
Any help you can provide would be greatly appreciated.

Best,
Tom

**Comment by maringos** [comment]
Hi Tom,

I am glad to help you. Please provide me with more details (e.g. which script, while line), so that I can replicate the issue.

Best,
Yorgos

**Comment by thh32** [comment]
This is using the SIHUMIx.R script and from the error I assume its line 234.

Looking further at the script, it could be the 'j' variable which is causing the issue as it is calling `commandArgs`, but none are given.

Best,
Tom

**Comment by maringos** [comment]
Hi,

I used a HPC system with arrays and each array has a number that is passed to the script through the `commandArgs`. 
It might be useful to use the command `Rscript SIHUMIx.R $nodes` in the command line, where $nodes is the number of the array.

Please let me know if I could help you more. I plan to update the instructions soon, so any feedback is more than welcome. 

Best,
Yorgos

**Comment by thh32** [comment]
Hey Yorgos,

That seems to have fixed the issue, thanks!

Its great to hear your planning to update the instructions. Clarifying this point would be very useful. I would also love it if you could provide the scripts you used to produce the papers figures, especially Figure 3, I think its a wonderful example of what can be done.

Best and thanks,
Tom

**Comment by maringos** [comment]
Hi Tom,

many thanks for your comments, indeed. In our [preprint](https://doi.org/10.1101/2024.06.11.598488 ), section 9 (line 502), we have stated where data and scripts can be found. 

```
The simulation RDS files that are related to this manuscript can be found on
Figshare (www.doi.org/10.6084/m9.figshare.25997962). The supporting information
including figures, scripts and datasets related to this manuscript can be found
on Figshare (www.doi.org/10.6084/m9.figshare.25998073).
```

Best,
Yorgos
